### ISSUE TITLE
Module 01 Unit 6 Create TestVM1

### ISSUE THREAD

**Issue by mrep1085** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#34]
# Module: 01
**Unit: 06
Task: 03
Step: 03**

Description of issue: Could not create TestVM1.
Windows Server 2022 Datacenter - **Gen2** does not support the **Standard_D2_v3** size that the table in the instructions mention. 
![image](https://user-images.githubusercontent.com/92067627/141072350-7d5f4177-1665-427c-8bcf-02edd820aa48.png)

Switching to Standard_D2s_v3 did not work either during validation with **Gen2**. The only way we got past validation was switching back to Windows Server 2022 Datacenter - **Gen1** using **D2_v3**.
![image](https://user-images.githubusercontent.com/92067627/141073970-2a980024-3d52-4382-afc2-189e603355b0.png)

Anything else and we were presented with the following error related to the policy.
![image](https://user-images.githubusercontent.com/92067627/141073699-0d5344f2-6fa1-4b5e-a64a-7d7c5b5357a4.png)

Any guidance on this?

**Comment by tiagocostapt** [comment]
The VM can be deployed with that Image/size.
Just tested and it works. The error you're getting is due to the lab provider that didn't allow that size. You get and error due to an Azure Policy. Open a ticket with the lab provider and tell then to fix it. 


![image](https://user-images.githubusercontent.com/11490197/141457074-83114c43-50dc-475c-b15a-2f4ff339d0a7.png)
![image](https://user-images.githubusercontent.com/11490197/141457098-0bc12794-92da-4a7c-8387-19c527267242.png)
