### ISSUE TITLE
ManufacturingVnet - created in westeurope 

### ISSUE THREAD

**Issue by belajarpowershell** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#37]
# Module: 00
#### Step: 00

Description of issue
ManufacturingVnet - created in location westeurope  , the location referenced in the training is North Europe.

azuredeploy.json

$RGName = "ContosoResourceGroup"

New-AzResourceGroupDeployment -ResourceGroupName $RGName -TemplateFile azuredeploy.json -TemplateParameterFile azuredeploy.parameters.json
URL with reference 
https://docs.microsoft.com/en-us/learn/modules/design-implement-hybrid-networking/3-exercise-create-configure-local-network-gateway

Repro steps:

1.
1.
1.

**Comment by jileary23** [comment]
Thank you. This bug was logged and fixed. The update will publish soon. In the future If you find bugs in MS Learn content, use the MS Learn feedback process: 

There is a link to report feedback at the bottom of each unit in a Learn module. This will allow you to send our teams communication about the content or Learn experience.

https://docs.microsoft.com/learn/support/troubleshooting#report-feedback
