### ISSUE TITLE
Module 4 Channel 9 Video Links Don't Work

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#72]
# Module: 03
#### Step: 00

Description of issue
The several links to Channel 9 Videos don't work.  I can't seem to find an alternative location of these videos.

Repro steps:

1.
1.
1.

Cheers,
Jeff

**Comment by arnoldvilleneuve** [comment]
Thank you. I am teaching this course this week. It is unfortunate that the author has left so many issues outstanding since last November.

**Comment by TesterTesterson1004** [comment]
I wanted to see if anyone who has watched the original video can confirm that this link is, in fact, identical:  https://sec.ch9.ms/ch9/82aa/de785143-470d-4394-9087-b0fd8cb482aa/ERCreateCkt_mid.mp4

I have never watched the video, however that link is listed on a site that is (in theory) a shorterm backup of content from the original Channel9 site: https://walkingcat.github.io/ch9-index/

At least based on its title it appears like the correct one:  
![image](https://user-images.githubusercontent.com/49700217/150236695-e2f7ceaf-2d1e-4db5-9505-ae37fd0bdc47.png)

If this is accurate, that file could be rehosted in another more permanent place on MSFT - while it is still available.

**Comment by arnoldvilleneuve** [comment]
Hey 
I am teaching this course this week as well. Can you reach out to me?
arnold at troposhere dot tech
Arnold Villeneuve 613-833-0984 

    On Wednesday, January 19, 2022, 06:50:33 p.m. EST, TesterTesterson1004 ***@***.***> wrote:  
 
 


I wanted to see if anyone who has watched the original video can confirm that this link is, in fact, identical: https://sec.ch9.ms/ch9/82aa/de785143-470d-4394-9087-b0fd8cb482aa/ERCreateCkt_mid.mp4

I have never watched the video, however that link is listed on a site that is (in theory) a shorterm backup of content from the original Channel9 site: https://walkingcat.github.io/ch9-index/

At least based on its title it appears like the correct one:


If this is accurate, that file could be rehosted in another more permanent place on MSFT - while it is still available.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JeffSmalley** [comment]
I never saw any of them but there are suppose to be 3 different videos:

 Azure ExpressRoute - **How to create an ExpressRoute circuit** | Azure | Channel 9 (msdn.com).
https://channel9.msdn.com/Blogs/Azure/Azure-ExpressRoute-How-to-create-an-ExpressRoute-circuit?term=ExpressRoute&lang-en=true&pageSize=15&skip=15

Azure ExpressRoute - **How to set up Azure private peering for your ExpressRoute circuit** | Azure | Channel 9 (msdn.com)
https://channel9.msdn.com/Blogs/Azure/Azure-ExpressRoute-How-to-set-up-Azure-private-peering-for-your-ExpressRoutecircuit?term=ExpressRoute&lang-en=true&pageSize=15&skip=15

Azure ExpressRoute **How to create a connection between your VPN Gateway and ExpressRoute circuit**
https://channel9.msdn.com/Blogs/Azure/Azure-ExpressRoute-How-to-create-a-connection-between-your-VPN-Gateway-and-
ExpressRoute-circuit?term=ExpressRoute&lang-en=true&pageSize=15&skip=15

Since this will be tough to demo for many MCTs  like me, these videos are pretty important if they are of good quality.

Happy Teaching,
Jeff Smalley MCT

**Comment by TesterTesterson1004** [comment]
OK, I believe I have links below that at least match the titles referenced exactly, and are thus hopefully what would have been in this course before the Channel9.msdn.com site was retired.  

Please note that I am *not* an expert on this technology, nor do I have any affiliation with the current GH repo ( https://walkingcat.github.io/ch9-index/ ) nor sec.ch9.ms sites...and I do not have any idea as to whether (or for how long)  this new repo will be live.


Azure ExpressRoute - How to create an ExpressRoute circuit:
https://sec.ch9.ms/ch9/82aa/de785143-470d-4394-9087-b0fd8cb482aa/ERCreateCkt_mid.mp4

Azure ExpressRoute - How to set up Azure private peering for your ExpressRoute circuit 
https://sec.ch9.ms/ch9/2f5f/193aca13-0950-4dbb-9dcc-f71abcc82f5f/ErPrivatePeering_mid.mp4

Azure ExpressRoute How to create a connection between your VPN Gateway and ExpressRoute circuit
https://sec.ch9.ms/ch9/5990/c3677297-81c3-4ea2-894e-2cfd5ee25990/ErVPNConnection_mid.mp4

**Comment by arnoldvilleneuve** [comment]
Well, I'm teaching this course this week. 

M02-Unit 3 Create and configure a virtual network gateway
Inbox
Task 2: Create CoreServicesTestVM

Hello 




I went through Unit 3 tonight. 





Attempt 1. Lab as presented. No go. 

Attempt 2. Change the PowerShell script to use "East US" instead of EastUS. No go. 

Attempt 3. I had to create a new template and parameter file for the first VM deployment. After that, things fell in line. You can find the template here. 




OneDrive for Business



| 
| 
|  | 
OneDrive for Business


 |

 |

 |







You will need to log in to your VM in a Private Mode Edge web browser with your Personal Email. Yes, I know I told you not to do that! Download the JSON files and replace the ones that are provided in the Allfiles\Exercises\M02 folder. I cannot do that for you. Continue with the lab. 




However, the deployment of the Virtual Private Gateway in Task 6 takes 45 minutes for a 2 hour lab. However, again, you can keep extending the lab time by 15 minutes as long as you are still working on the lab. 


Arnold Villeneuve 
 

    On Wednesday, January 19, 2022, 08:29:26 p.m. EST, TesterTesterson1004 ***@***.***> wrote:  
 
 


OK, I believe I have links below that at least match the titles referenced exactly, and are thus hopefully what would have been in this course before the Channel9.msdn.com site was retired.

Please note that I am not an expert on this technology, nor do I have any affiliation with the current GH repo ( https://walkingcat.github.io/ch9-index/ ) nor sec.ch9.ms sites...and I do not have any idea as to whether (or for how long) this new repo will be live.

Azure ExpressRoute - How to create an ExpressRoute circuit:
https://sec.ch9.ms/ch9/82aa/de785143-470d-4394-9087-b0fd8cb482aa/ERCreateCkt_mid.mp4

Azure ExpressRoute - How to set up Azure private peering for your ExpressRoute circuit
https://sec.ch9.ms/ch9/2f5f/193aca13-0950-4dbb-9dcc-f71abcc82f5f/ErPrivatePeering_mid.mp4

Azure ExpressRoute How to create a connection between your VPN Gateway and ExpressRoute circuit
https://sec.ch9.ms/ch9/5990/c3677297-81c3-4ea2-894e-2cfd5ee25990/ErVPNConnection_mid.mp4

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by arnoldvilleneuve** [comment]
To be honest, I never use these videos in my course events. There is just not enough time if you are also trying to do the lab exercises with the students during the course. 
Arnold Villeneuve 613-833-0984 

    On Wednesday, January 19, 2022, 08:13:35 p.m. EST, JeffSmalley ***@***.***> wrote:  
 
 


I never saw any of them but there are suppose to be 3 different videos:

Azure ExpressRoute - How to create an ExpressRoute circuit | Azure | Channel 9 (msdn.com).
https://channel9.msdn.com/Blogs/Azure/Azure-ExpressRoute-How-to-create-an-ExpressRoute-circuit?term=ExpressRoute&lang-en=true&pageSize=15&skip=15

Azure ExpressRoute - How to set up Azure private peering for your ExpressRoute circuit | Azure | Channel 9 (msdn.com)
https://channel9.msdn.com/Blogs/Azure/Azure-ExpressRoute-How-to-set-up-Azure-private-peering-for-your-ExpressRoutecircuit?term=ExpressRoute&lang-en=true&pageSize=15&skip=15

Azure ExpressRoute How to create a connection between your VPN Gateway and ExpressRoute circuit
https://channel9.msdn.com/Blogs/Azure/Azure-ExpressRoute-How-to-create-a-connection-between-your-VPN-Gateway-and-
ExpressRoute-circuit?term=ExpressRoute&lang-en=true&pageSize=15&skip=15

Since this will be tough to demo for many MCTs like me, these videos are pretty important if they are of good quality.

Happy Teaching,
Jeff Smalley MCT

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
