### ISSUE TITLE
M02Unit3Task1 and 2 powershell script to create coreservicevnet does not work

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#73]
# Module: 02
#### Step: 03

Description of issue

East US should be EastUS or "East US". 

Either way, neither deployment of the underlying VNet templates worked for the four students nor me. The Virtual network	CoreServicesVnet could not be selected. 

Solution

M02-Unit 3 Create and configure a virtual network gateway
Inbox

Task 2: Create CoreServicesTestVM

I went through Unit 3 tonight. 

Attempt 1. Lab as presented. No go. 

Attempt 2. Change the PowerShell script to use "East US" with quotes instead of EastUS (which we also tried). No go. 

Attempt 3. I had to create a new template and parameter file for the first VM deployment. After that, things fell in line. You can find the attached template. 

You will need to log in to your VM in a Private Mode Edge web browser with your Personal Email. Yes, I know I told you not to do that! Download the JSON files and replace the ones that are provided in the Allfiles\Exercises\M02 folder. I cannot do that for you. Continue with the lab. 

However, the deployment of the Virtual Private Gateway in Task 6 takes 45 minutes for a 2-hour
[Mod2Unit3Task2_CreatVMJsonTemplate (1).zip](https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions/files/7901687/Mod2Unit3Task2_CreatVMJsonTemplate.1.zip)
 lab. However, again, you can keep extending the lab time by 15 minutes as long as you are still working on the lab.

**Comment by arnoldvilleneuve** [comment]
Note: My template only recreates the CoreServicesVnet vnet object instance. We ended up copying the three vnet configuations and recreated them manually. That worked.

**Comment by JeffSmalley** [comment]
I am having the same issue of the VNET existing but NOT showing as an option when creating the first Virtual Machine.  Instead of using the PowerShell in the CloudShell, I did a graphical deployment using the "Deploy a Custom Template" tool without the parameter file and it worked. When creating the Virtual Machine it now sees the CoreServicesVent.   This all maybe some temporary Azure clitch.

At least fix the issue the PowerShell of East US should be "East US" for now since that is definitely a mistake.

When prepping Module 4's lab and had a similar issue with a deployed NSG called "MyNSG" being deployed via PowerShell but not showing up when I was creating the test VM in Task 5.  The MyNSG just allows inbound RDP 3389 from anywhere which you can create on the fly in the VM creation but opening Port 3389 in the networking section.

Cheers,
Jeff Smalley  MCT
Chicagoville

 Thanks for posting this Arnold..

**Comment by arnoldvilleneuve** [comment]
Glad it helped another Instructor. I did similar approaches but it all takes time to resolve.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JeffSmalley** [comment]
One method that seems fix the issue of the VNET not showing up when creating the Virtual Machine is to not deploy the ARM Template via PowerShell.   I did create the Resource Group via PowerShell, then I deployed the Resource template via the Deploy a Custom Template graphical tool. I did NOT add the Parameter file since it doesn't change anything from the original. I tried this a couple times and it seems to work.  If the VNETs were deployed via the PowerShell just delete them before trying the graphical technique.     I have NO idea why this is happening..

Please can someone at least fix the issue with the PowerShell script with East US not being quoted or remove the space.  "East US"   or EastUS

Thanks,
Jeff Smalley  MCT

Jeff Smalley

**Comment by arnoldvilleneuve** [comment]
That is what I did as well, but make sure you deploy all three Vnets and their respective subnets at the same time. 
Arnold Villeneuve 613-833-0984 

    On Monday, January 24, 2022, 05:06:33 p.m. EST, JeffSmalley ***@***.***> wrote:  
 
 


One method that seems fix the issue of the VNET not showing up when creating the Virtual Machine is to not deploy the ARM Template via PowerShell. I did create the Resource Group via PowerShell, then I deployed the Resource template via the Deploy a Custom Template graphical tool. I did NOT add the Parameter file since it doesn't change anything from the original. I tried this a couple times and it seems to work. If the VNETs were deployed via the PowerShell just delete them before trying the graphical technique. I have NO idea why this is happening..

Please can someone at least fix the issue with the PowerShell script with East US not being quoted or remove the space. "East US" or EastUS

Thanks,
Jeff Smalley MCT

Jeff Smalley

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.
